In [16]:
from sklearn import tree
import numpy as np
import pandas as pd

In [17]:
dataset = pd.read_csv("dataset.csv")

In [18]:
dataset.head()

Kecamatan  Tidak/Belum Sekolah  Belum Tamat SD  Tamat SD  SLTP  SLTA  \
0  Sukasari                 2275            1173      1900  1648  3735   
1  Sukasari                 3850            2038      2068  2450  6924   
2  Sukasari                 2412            1289      1740  1608  4073   
3  Sukasari                 4525            2462      2137  2545  8416   
4   Coblong                 1820            1055      1121  1406  4494   

   D1 dan D2    D3    S1   S2   S3  
0        108   469  1633  288   43  
1        348  1280  3662  640  115  
2        120   502  1557  205   60  
3        380  1703  4503  633   84  
4         58   399  1200  103   25

In [19]:
dataset['Kecamatan'] = pd.factorize(dataset.Kecamatan)[0]

In [20]:
dataset.tail()

Kecamatan  Tidak/Belum Sekolah  Belum Tamat SD  Tamat SD  SLTP  SLTA  \
145         29                 1010             534       629   809  1915   
146         29                 1331             706      1016  1118  2092   
147         30                 5224            2754      3382  3755  8277   
148         30                 3602            1798      2137  2645  6146   
149         30                 2577            1403      1961  1942  3956   

     D1 dan D2   D3    S1   S2  S3  
145         31  163   414   24   7  
146         36  221   736  121  12  
147         98  820  2207  209  19  
148         80  548  1589  149   6  
149         39  329   948   90  16

In [21]:
dataset = dataset.to_numpy()

In [22]:
print(dataset)

[[   0 2275 1173 ... 1633  288   43]
 [   0 3850 2038 ... 3662  640  115]
 [   0 2412 1289 ... 1557  205   60]
 ...
 [  30 5224 2754 ... 2207  209   19]
 [  30 3602 1798 ... 1589  149    6]
 [  30 2577 1403 ...  948   90   16]]


In [23]:
dataTraining = np.concatenate((dataset[0:60, :], dataset[75:135, :]), axis=0)
dataTesting = np.concatenate((dataset[60:75, :], dataset[135:150, :]), axis=0)

In [24]:
print(dataTraining)
len(dataTraining)

[[   0 2275 1173 ... 1633  288   43]
 [   0 3850 2038 ... 3662  640  115]
 [   0 2412 1289 ... 1557  205   60]
 ...
 [  26 3464 1887 ... 1146   96   18]
 [  26 3281 1963 ... 1276  108   17]
 [  26 3801 2169 ... 1658  187   23]]


120

In [25]:
print(dataTesting)
len(dataTesting)

[[  12 1413  766  628 1191 3492   35  454 1152   98   13]
 [  12 2272 1353 1368 2497 5613   52  415 1053   82    9]
 [  12 1544  864  856 1762 3773   42  290  659   30    3]
 [  12 2233 1302 1311 2113 5153   55  314  789   23    4]
 [  12 3044 1875 2165 3160 6977   64  440 1279   78    5]
 [  13 1778 1188  780 1081 3089  149  694 2725  473   58]
 [  13 1563  887  445  928 4068  186  601 1390  164   22]
 [  13 1595  909  822 1203 3357  170  589 1153  154   18]
 [  13  849  556  451  812 2265  124  313  781   66    6]
 [  13 2081 1444  690 1301 3668  225 1012 3869  860  131]
 [  13 1304  814  760 1081 2711  132  358 1143  185   12]
 [  13 1418  889  809 1190 3284  149  384  816   70    9]
 [  14 3033 1632 1551 2637 6253  206  589 1398  117    9]
 [  14 3943 2049 2285 3359 7976  270  878 2080  203   28]
 [  14 2914 1406 1327 2370 6002  143  585 1371  100    9]
 [  27  873  501  680  636  899   43  167  438   40    6]
 [  27 3795 1875 1970 2920 5794  231 1074 2996  427   57]
 [  27 2190 12

30

In [26]:
inputTraining = dataTraining[:,0:10]
inputTesting = dataTesting[:,0:10]
labelTraining = dataTraining[:,10]
labelTesting = dataTesting[:,10]
print(labelTraining)
len(labelTraining)

[ 43 115  60  84  25  20  27 180  54   6   7  11   6  19   3   8  17   7
   6   2  15   8   9   8   7   3  10  15  15  28  15  17  47  46  24  28
  55  13  36  48  22  43  50  40   9   4   2   1   6   6  33  31   6  10
  11  16  17  41   6  11  17  33  37  24   5  16  21   0  36   1   4  13
   2   8  14  21   5   6  15   4   4   7   7  34  60  20 181  10  24  17
   8  43  61  97  45  48   0  17  24  98  62  38  42  51  16  99  33 127
  11  55  65  28  56  34  14  48  33  18  17  23]


120

In [27]:
model = tree.DecisionTreeClassifier()

In [28]:
model =  model.fit(inputTraining, labelTraining)

In [29]:
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [ 13   9   3   4   5  58  22  18   6 131  12   9   9  28   9   6  57  25
  11  25  63   0  21   8  11   7  12  19   6  16]
Hasil Prediksi :  [20  9  0  0  6 60 17 15 10 60 60 16 15 36 15  2 55 31 40 18 60  6 20 10
  2  6 20 33 10  7]


In [30]:
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar : ", prediksiBenar, " Data")
print("Prediksi Salah : ", prediksiSalah, " Data")
print("Akurasi : ", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar :  1  Data
Prediksi Salah :  29  Data
Akurasi :  3.3333333333333335 %
